dist: xenial
sudo: required
env:
  global:
    - DOCKER_REPO=dockerpirate/unbound
    - ALPINE_M=3
    - ALPINE_P=12
before_install:
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --build-arg ALPINE_M --use
script: bash ci.sh
